#!/bin/bash

#PBS -N lumpy_call_sampleReplace
#PBS -l nodes=1:ppn=1
#PBS -l mem=20gb
#PBS -q analysis
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/lumpy/lumpy_call.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/lumpy/lumpy_call.out
#PBS -A proj-as0001

source activate python2

tool=lumpy
sample=sampleReplace
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample
outputDir=$workingDir/callers/$tool
preprocessDir=$outputDir/preprocess
tempDir=$outputDir/temp/${tool}_call
output=$outputDir/$tool.vcf
inputDir=$rootDir/data
input=$inputDir/$sample.hgv.bam
helperDir=$rootDir/scripts/helpers
excludeBed=$helperDir/human.hs37d5.excl.bed
progressFile=$workingDir/log/progress.txt

mkdir -p $tempDir
cd $outputDir

# check input
for file in $input $input.bai $preprocessDir/discordants.bam $preprocessDir/splitters.bam; do
    if [[ ! -s $file ]]; then
        echo "File $file does not exist, exit" >&2
        echo "ERROR: ${tool}_call" >> $progressFile
        exit 1
    fi
done

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_call.......... on $ho, from $start" >> $progressFile

############################################################

lumpyexpress \
    -B $input \
    -S $preprocessDir/splitters.bam \
    -D $preprocessDir/discordants.bam \
    -o $output \
    -x $excludeBed \
    -T $tempDir

# check error
if [[ ! $? -eq 0 ]]; then
    echo "ERROR: ${tool}_call" >> $progressFile
    exit 1
fi

vcf-sort -c $output \
| awk -v FS="\t" -v OFS="\t" -v s=$sample '$1~/^#CHROM/ {$NF=s} {print $0}' > $output.2
mv $output.2 $output

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_call, $diffInWord" >> $progressFile


