#!/bin/bash

#PBS -N manta_call_sampleReplace
#PBS -l nodes=1:ppn=10
#PBS -l mem=80gb
#PBS -q analysis
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/manta/manta_call.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/manta/manta_call.out
#PBS -A proj-as0001

source activate python2

tool=manta
sample=sampleReplace
threads=12
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample
outputDir=$workingDir/callers/$tool
output=$outputDir/$tool.vcf
inputDir=$rootDir/data
input=$inputDir/$sample.hgv.bam
helperDir=$rootDir/scripts/helpers
reference=$helperDir/hs37d5/hs37d5.fa
progressFile=$workingDir/log/progress.txt

mkdir -p $outputDir
cd $outputDir

# check input
if [[ ! -s $input ]] || [[ ! -s $input.bai ]]; then
    echo "File $input or index does not exist, exit" >&2
    echo "ERROR: ${tool}_call" >> $progressFile
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_call.......... on $ho, from $start" >> $progressFile

############################################################

region_string=""
for chr in {1..22} X Y; do
    region_string="$region_string --region=$chr"
done

configManta.py \
--referenceFasta $reference \
--bam $input \
--runDir $outputDir \
$region_string

$outputDir/runWorkflow.py -m local -j $threads

# check error
if [[ ! $? -eq 0 ]]; then
    echo "ERROR: ${tool}_call" >> $progressFile
    exit 1
fi

vcf-sort -c $outputDir/results/variants/diploidSV.vcf.gz \
| awk -v FS="\t" -v OFS="\t" -v s=$sample '$1~/^#CHROM/ {$NF=s} {print $0}' > $output.2
mv $output.2 $output

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_call, $diffInWord" >> $progressFile


