#!/bin/bash

#PBS -N breakdancer_call_sampleReplace
#PBS -l nodes=1:ppn=10
#PBS -l mem=80gb
#PBS -q analysis
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/breakdancer/breakdancer_call.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/breakdancer/breakdancer_call.out
#PBS -A proj-as0001

module load perl/5.18.2

threads=12
sample=sampleReplace
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample
outputDir=$workingDir/callers/breakdancer
tempDir=$outputDir/temp/breakdancer_call
output=$outputDir/breakdancer
inputDir=$rootDir/data
input=$inputDir/$sample.hgv.bam
helperDir=$rootDir/scripts/helpers
bam2cfg=$helperDir/breakdancer-maxunstable/bam2cfg.pl
breakdancer2vcf=$helperDir/breakdancer2vcf.py
progressFile=$workingDir/log/progress.txt

mkdir -p $tempDir
cd $outputDir

# check input
if [[ ! -f $input ]]; then
    echo "File $input does not exist, exit"
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: breakdancer_call.......... on $ho, from $start" >> $progressFile

############################################################

$bam2cfg $input > $tempDir/breakdancer.cfg
cmdFile=$tempDir/breakdancer.cmd
if [[ -f $cmdFile ]]; then rm $cmdFile; fi

echo "breakdancer-max $tempDir/breakdancer.cfg $input -t > $tempDir/breakdancer-BND.ctx" > $cmdFile
for chr in {1..22} X Y; do
    echo "breakdancer-max $tempDir/breakdancer.cfg $input -o $chr > $tempDir/breakdancer-$chr.ctx" >> $cmdFile
done

parallel -j $threads -a $cmdFile eval

cp $tempDir/breakdancer-1.ctx $output.ctx
for chr in {2..22} X Y; do
    awk '$1!~/^#/' $tempDir/breakdancer-$chr.ctx >> $output.ctx
done
# also remove minor chr for BND
awk '$1!~/^#/ && $1~/^[0-9]+$|^X$|^Y$/ && $4~/^[0-9]+$|^X$|^Y$/' $tempDir/breakdancer-BND.ctx >> $output.ctx

source activate python2
$breakdancer2vcf -i $output.ctx -o $output.vcf
vcf-sort -c -p $threads $output.vcf > $output.vcf.2
mv $output.vcf.2 $output.vcf

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: breakdancer_call, $diffInWord" >> $progressFile





 
