#!/bin/bash

#PBS -N delly_categorize_sampleReplace
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -q analysis
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/delly/delly_categorize.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/delly/delly_categorize.out
#PBS -A proj-as0001

tool=delly
sample=sampleReplace
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample/callers/$tool
outputDir=$workingDir/categorize
input=$workingDir/$tool.vcf
helperDir=$rootDir/scripts/helpers
addMateInfo=$helperDir/addMateInfoForBND.py
progressFile=$rootDir/sample/$sample/log/progress.txt

mkdir -p $outputDir
cd $outputDir

# check input
if [[ ! -s $input ]]; then
    echo "File $input does not exist, exit"
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_categorize.......... on $ho, from $start" >> $progressFile

############################################################

## categorize by SV type
for ty in DUP DEL INV BND; do
    type="\"$ty\""
    if [[ $ty == "BND" ]]; then
        ty=CTX
    fi
    bcftools view -i "INFO/SVTYPE==$type" $input > $outputDir/delly.$ty.vcf
    if [[ $ty == "CTX" ]]; then
        $addMateInfo $outputDir/delly.$ty.vcf | sed "s/SVTYPE==BND/SVTYPE==$ty/" \
        > $outputDir/delly.$ty.vcf.2
        mv $outputDir/delly.$ty.vcf.2 $outputDir/delly.$ty.vcf
    fi
    bcftools view -f PASS -i '(FMT/GT="0/1" | FMT/GT="1/1") & FMT/FT="PASS"' $outputDir/delly.$ty.vcf \
    > $outputDir/delly.$ty.simpleFilter.vcf
done

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_categorize, $diffInWord" >> $progressFile




