#!/bin/bash

#PBS -N cnvnator_call_sampleReplace
#PBS -l nodes=1:ppn=10
#PBS -l mem=80gb
#PBS -q analysis
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_call.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_call.out
#PBS -A proj-as0001

module load perl/5.18.2
module load CNVnator

tool=cnvnator
sample=sampleReplace
threads=12
binSize=100
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample
outputDir=$workingDir/callers/$tool
tempDir=$outputDir/temp/${tool}_call
outputFile=$outputDir/$tool.vcf
inputDir=$rootDir/data
input=$inputDir/$sample.hgv.bam
helperDir=$rootDir/scripts/helpers
chrDir=$helperDir/hs37d5_chr
cnvnator2VCF=$helperDir/cnvnator2VCF.pl
progressFile=$workingDir/log/progress.txt

mkdir -p $tempDir
cd $outputDir

# check input
if [[ ! -s $input ]] || [[ ! -s $input.bai ]]; then
    echo "File $input or index does not exist, exit" >&2
    echo "ERROR: ${tool}_call" >> $progressFile
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_call.......... on $ho, from $start" >> $progressFile

############################################################

cmdFile=$tempDir/cnvnator.cmd
if [[ -f $cmdFile ]]; then rm $cmdFile; fi

for contig in {1..22} X Y; do
    rootFile=$tempDir/root.$contig
    output=$tempDir/cnvnator_call.$contig
    echo "cnvnator -root $rootFile -chrom $contig -tree $input -unique; cnvnator -root $rootFile -chrom $contig -his $binSize -d $chrDir; cnvnator -root $rootFile -chrom $contig -stat $binSize; cnvnator -root $rootFile -chrom $contig -partition $binSize; cnvnator -root $rootFile -chrom $contig -call $binSize > $output; $cnvnator2VCF $output $chrDir > $output.vcf" >> $cmdFile
done

parallel -j $threads -a $cmdFile eval

# check error
if [[ ! $? -eq 0 ]]; then
    echo "ERROR: ${tool}_call" >> $progressFile
    exit 1
fi

cp $tempDir/cnvnator_call.1.vcf $outputFile
for chr in {2..22} X Y; do
	awk '$1!~/^#/' $tempDir/cnvnator_call.$chr.vcf >> $outputFile
done

vcf-sort -c -p $threads $outputFile \
| awk -v FS="\t" -v OFS="\t" -v s=$sample '$1~/^#CHROM/ {$NF=s} {print $0}' > $outputFile.2
mv $outputFile.2 $outputFile

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_call, $diffInWord" >> $progressFile


