#!/bin/bash

#PBS -N cnvnator_categorize_sampleReplace
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -q analysis
#PBS -V
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_categorize.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_categorize.out
#PBS -A proj-as0001

tool=cnvnator
sample=sampleReplace
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample/callers/$tool
outputDir=$workingDir/categorize
input=$workingDir/$tool.vcf
progressFile=$rootDir/sample/$sample/log/progress.txt

mkdir -p $outputDir
cd $outputDir

# check input
if [[ ! -f $input ]]; then
    echo "File $input does not exist, exit"
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_call.......... on $ho, from $start" >> $progressFile

############################################################

## categorize by SV type
for ty in DUP DEL; do
    type="\"$ty\""
    bcftools view -i "INFO/SVTYPE==$type" $input > $inputDir/categorize/cnvnator.$ty.vcf
    cp $inputDir/categorize/cnvnator.$ty.vcf $inputDir/categorize/cnvnator.$ty.simpleFilter.vcf
done

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_categorize, $diffInWord" >> $progressFile



