#!/bin/bash

#PBS -N cnvnator_categorize_sampleReplace
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -q analysis
#PBS -V
#PBS -d /users/hl7/analysis/SV/sample/sampleReplace
#PBS -e /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_categorize.err
#PBS -o /users/hl7/analysis/SV/sample/sampleReplace/log/cnvnator/cnvnator_categorize.out
#PBS -A proj-as0001

tool=cnvnator
sample=sampleReplace
sizeMin=100
sizeMax=1000000
rootDir=/users/hl7/analysis/SV
workingDir=$rootDir/sample/$sample/callers/$tool
outputDir=$workingDir/categorize
input=$workingDir/$tool.vcf
helperDir=$rootDir/scripts/helpers
excludeRegion=$helperDir/RLCRs_no_Repeat_Masker.txt
progressFile=$rootDir/sample/$sample/log/progress.txt

mkdir -p $outputDir
cd $outputDir

# check input
if [[ ! -s $input ]]; then
    echo "File $input does not exist, exit"
    exit 1
fi

##########################################################

ho=$(hostname)
start=$(date)
startTime=$(date -u +"%s")
echo "Running: ${tool}_categorize.......... on $ho, from $start" >> $progressFile

############################################################

## categorize by SV type
for ty in DUP DEL; do
    type="\"$ty\""
    bcftools view -i "INFO/SVTYPE==$type" $input > $outputDir/$tool.$ty.vcf
    cp $outputDir/$tool.$ty.vcf $outputDir/$tool.$ty.simpleFilter.vcf
done

## further filter
for ty in DUP DEL; do
    bcftools query -f '%CHROM\t%POS\t%INFO/END\n' $outputDir/$tool.$ty.simpleFilter.vcf \
    | bedtools intersect -a stdin -b $excludeRegion -v \
    | sort -k1V,1V -k2n,2n -k3n,3n \
    > $outputDir/$tool.$ty.furtherFilter.bed
done

#############################################################

finish=$(date)
finishTime=$(date -u +"%s")
diff=$(($finishTime-$startTime))
hour=$(($diff/3600))
diffInWord=`echo "$hour hours $((($diff-$hour*3600)/60)) minutes and $((($diff-$hour*3600)%60)) seconds elapsed"`
echo "Done: ${tool}_categorize, $diffInWord" >> $progressFile


